version: "3.8"
services:
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "8081:8081"
      - "9001:9001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  polar-postgres:
    image: "postgres:13"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  config-service:
    depends_on:
      - polar-postgres
    image: "config-service"
    container_name: "config-service"
    ports:
      - "9002:9002"
      - "8888:8888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9002
  order-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "order-service"
    container_name: "order-service"
    ports:
      - "9003:9003"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - "6379:6379"
  edge-service:
    depends_on:
      - polar-postgres
      - config-service
      - polar-redis
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - "9999:9999"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATA_REDIS_HOST=polar-redis
  polar-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672 # The port where RabbitMQ listens for AMQP requests
      - 15672:15672 # The port that exposes the management GUI
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  dispatcher-service:
    depends_on:
      - polar-postgres
      - config-service
      - polar-rabbitmq
    image: "dispatcher-service"
    container_name: "dispatcher-service"
    ports:
      - "9004:9004"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - ORDER_SERVICE_URL=http://order-service:9003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - REDIS_URL=polar-redis
