POST http://localhost:8081/books
Content-Type: application/json

{
  "author": "{{$random.alphanumeric(10)}}",
  "isbn": "{{$random.uuid}}",
  "price": {{$random.float}},
  "title": "{{$random.alphabetic(20)}}"
}

###
GET http://localhost:8081/books
Accept: application/json

### Orders
POST http://localhost:9003/orders
Content-Type: application/json

{
  "isbn": "1234567891",
  "quantity": 3
}

###

GET http://localhost:8081/books
Accept: application/json
