spring:
  application:
    name: catalog-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 500
      retry:
        max-attempts: 10
        multiplier: 10
        initial-interval: 100
        max-interval: 5000
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8081
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 15
      min-spare: 5

polar:
  testdata:
    enabled: true


