spring:
  application:
    name: catalog-service

server:
  port: 8081
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 15
      min-spare: 5

polar:
  greeting: Welcome to the local book catalog!
